// ─── الترجمة الإنجليزية ─────────────────────────────────────────────────────
// المفتاح هو النصّ العربي كما يظهر في التطبيق. ما لم يُترجَم يظهر عربياً.
export default {
    // ─ عام
    'عُهدة': 'Ohda',
    'عهدة': 'Custody',
    'عُهدتك ومصاريفك وإيصالاتك في مكانٍ واحد': 'Your custody funds, expenses and receipts in one place',
    'الرئيسية': 'Home', 'الحركات': 'Transactions', 'العُهد': 'Funds', 'الميزانية': 'Budget', 'الإعدادات': 'Settings',
    'مصروف جديد': 'New expense', 'استلام مبلغ': 'Receive money', 'استلام': 'Received', 'مصروف': 'Expense',
    'خروج': 'Sign out', 'رجوع': 'Back', 'إغلاق': 'Close', 'تغيير اللغة': 'Change language',
    'حفظ': 'Save', 'حذف': 'Delete', 'تعديل': 'Edit', 'إزالة': 'Remove', 'إضافة': 'Add', 'مسح': 'Clear', 'مسح الكل': 'Clear all',
    'الكل': 'All', 'نعم': 'Yes', 'لا': 'No', 'بلا': 'None', 'من': 'From', 'إلى': 'To', 'اليوم': 'Today', 'أمس': 'Yesterday',
    'ر.س': 'SAR', 'العربية': 'العربية',
    'نقداً': 'Cash', 'بطاقة': 'Card', 'تحويل': 'Transfer',
    'عهدة عمل': 'Work custody', 'ميزانية': 'Budget', 'مصاريف شخصية': 'Personal expenses',

    // ─ الدخول
    'اسمك': 'Your name', 'اسم الدخول': 'Username', 'كلمة المرور': 'Password', 'دخول': 'Sign in',
    'أنشئ حساب المدير': 'Create admin account',
    'حروف إنجليزية صغيرة وأرقام': 'Lowercase English letters and numbers',
    'ثمانية أحرف فأكثر': 'At least 8 characters',
    'أوّل حساب يُنشأ هنا هو المدير: يضيف المستخدمين ويربط Google Drive. وتُغلق هذه الصفحة بعده.':
        'The first account created here is the admin: it adds users and links Google Drive. This page closes after that.',
    'الحسابات يُنشئها المدير — اطلب منه اسم دخولك': 'Accounts are created by the admin — ask them for your username',
    'تعذّر الدخول': 'Could not sign in',

    // ─ الرئيسية
    'هذا الشهر': 'This month', 'الشهر الماضي': 'Last month', 'الربع': 'Quarter', 'السنة': 'Year', 'كل الفترات': 'All time',
    'كل العُهد': 'All funds', 'المصروف': 'Spent', 'المستلم': 'Received', 'ضريبة القيمة المضافة': 'VAT',
    'بلا إيصال': 'No receipt', 'متوسط اليوم': 'Daily average',
    '{n} حركة': '{n} transactions', '{p}٪ عن الفترة السابقة': '{p}% vs previous period',
    'تجاوزتَ ميزانية {c} هذا الشهر:': 'You exceeded the {c} budget this month:',
    'اقتربتَ من ميزانية {c} هذا الشهر:': 'You are close to the {c} budget this month:',
    '{n} مصروفٍ بلا إيصال — أرفقها قبل التصفية': '{n} expenses without a receipt — attach them before settlement',
    'أرصدة العُهد': 'Fund balances', 'مستلم': 'Received',
    'لا حركات في هذه الفترة': 'No transactions in this period',
    'صوّر أول إيصال ويقرأه التطبيق لك: الجهة والتاريخ والمبلغ والضريبة.': 'Snap your first receipt and the app reads it for you: vendor, date, amount and VAT.',
    'أين ذهب المال': 'Where the money went', '{n} تصنيف': '{n} categories',
    'المصروف يوماً بيوم': 'Daily spending', 'المصروف شهراً بشهر': 'Monthly spending',
    'ميزانيات هذا الشهر': "This month's budgets", 'أكثر الجهات صرفاً': 'Top vendors', '{n} مرّة': '{n}×',
    'لا جهات مسجّلة بعد': 'No vendors yet', 'طرق الدفع': 'Payment methods',
    'آخر الحركات': 'Recent transactions', 'عرض الكل': 'View all', 'لا حركات بعد': 'No transactions yet',
    'بلا تصنيف': 'Uncategorised',

    // ─ الحركات
    'ابحث بالجهة أو الملاحظة أو المرجع': 'Search vendor, note or reference', 'تصفية': 'Filter',
    'كشف PDF': 'PDF statement', 'تصدير Excel': 'Export Excel', 'السلّة': 'Trash',
    'تصنيف': 'Category', 'السلّة فارغة': 'Trash is empty', 'لا حركات تطابق': 'No matching transactions',
    'ما تحذفه يبقى هنا ويُستعاد متى شئت.': 'Whatever you delete stays here and can be restored anytime.',
    'جرّب إزالة بعض المرشِّحات.': 'Try removing some filters.', 'سجّل أول مصروف وسيظهر هنا.': 'Record your first expense and it will appear here.',
    'استعادة': 'Restore', 'استُعيدت الحركة': 'Transaction restored',
    'التاريخ': 'Date', 'الجهة': 'Vendor', 'التصنيف': 'Category', 'العهدة': 'Fund', 'الدفع': 'Payment',
    'الضريبة': 'VAT', 'المبلغ': 'Amount', 'النوع': 'Type', 'طريقة الدفع': 'Payment method', 'المرجع': 'Reference',
    'ملاحظة': 'Note', 'إيصال': 'Receipt',
    'تصفية الحركات': 'Filter transactions', 'كل التصنيفات': 'All categories',
    'المصاريف التي بلا إيصال فقط': 'Only expenses without a receipt', 'عرض النتائج': 'Show results',

    // ─ نموذج الحركة
    'تفاصيل الحركة': 'Transaction details',
    'تعذّر رفع الملف': 'Could not upload the file', 'تعذّرت القراءة': 'Could not read the receipt',
    'أكمل البيانات يدوياً': 'please complete the details manually', 'اكتب المبلغ': 'Enter the amount',
    'تعذّر الحفظ': 'Could not save',
    'حُفظت التعديلات': 'Changes saved', 'سُجّل المصروف': 'Expense recorded', 'سُجّل الاستلام': 'Receipt of money recorded',
    'نقل الحركة إلى السلّة؟ تُستعاد منها متى شئت.': 'Move this transaction to the trash? You can restore it anytime.',
    'نُقلت إلى السلّة': 'Moved to trash',
    'مستند PDF — اضغط للعرض': 'PDF document — tap to view', 'الإيصال': 'Receipt',
    'إعادة التصوير': 'Retake', 'يُرفع الملف…': 'Uploading…', 'يقرأ الإيصال…': 'Reading the receipt…',
    'يُرفع…': 'Uploading…', 'صوّر الإيصال': 'Scan receipt', 'صورة أو PDF': 'Image or PDF',
    'يقرأ التطبيق الجهة والتاريخ والمبلغ والضريبة من الإيصال': 'The app reads the vendor, date, amount and VAT from the receipt',
    'قُرئ الإيصال': 'Receipt read', 'قراءة واضحة': 'Clear read', 'راجع الأرقام': 'Check the figures',
    'قراءة ضعيفة — راجعها': 'Weak read — please check', '{n} بنود': '{n} items',
    'الضريبة (١٥٪)': 'VAT (15%)', 'احسب من المبلغ: {v}': 'Calculate from amount: {v}',
    'رقم التحويل': 'Transfer number', 'المصدر': 'Source',
    'المتجر أو المحطّة أو المدرسة': 'Store, station or school', 'من سلّمك المبلغ': 'Who gave you the money',
    'من عهدة': 'From fund', 'إلى عهدة': 'To fund', 'رقم الفاتورة أو المرجع': 'Invoice number or reference',
    'حفظ التعديلات': 'Save changes', 'حفظ وإضافة آخر': 'Save & add another',
    'يبدو أنها مسجّلة من قبل': 'This looks like a duplicate',
    'سُجّل من قبل: {v} بتاريخ {d} بمبلغ': 'Already recorded: {v} on {d} for',
    'بنفس اليوم والجهة والمبلغ.': 'same day, vendor and amount.',
    'لا، ألغِ': 'No, cancel', 'سجّلها مرّة ثانية': 'Record it again', 'افتح المسجَّلة': 'Open the existing one',

    // ─ العُهد
    'لكل غرضٍ عهدته ورصيده المستقل': 'Each purpose has its own fund and balance', 'عهدة جديدة': 'New fund',
    'لا عُهد بعد': 'No funds yet', 'أنشئ عهدة لكل غرض، واستلم فيها المبالغ وسجّل منها المصاريف.': 'Create a fund for each purpose, receive money into it and record expenses from it.',
    'عُهدٌ مُصفّاة': 'Settled funds', 'مُصفّاة': 'Settled', 'مفتوحة': 'Open', 'الرصيد': 'Balance',
    'حُفظت العهدة': 'Fund saved', 'أُنشئت العهدة': 'Fund created', 'تعديل العهدة': 'Edit fund', 'الاسم': 'Name',
    'عهدة العمل، مصاريف المدارس…': 'Work custody, school expenses…', 'اللون': 'Colour',
    'كشف العهدة': 'Fund statement', 'الرصيد المتبقّي': 'Remaining balance',
    'تصفية العهدة؟ تُقفل فلا تظهر في الإدخال، ولا يُحذف منها شيء — وتُعاد فتحها متى شئت.':
        'Settle this fund? It will be closed for new entries; nothing is deleted and you can reopen it anytime.',
    'أُعيد فتح العهدة': 'Fund reopened', 'صُفّيت العهدة': 'Fund settled',
    'كشف حساب PDF': 'PDF statement', 'تقرير التصفية': 'Settlement report', 'إعادة فتح': 'Reopen', 'تصفية العهدة': 'Settle fund',
    'العهدة فارغة': 'This fund is empty', 'ابدأ باستلام المبلغ المسلَّم لك، ثم سجّل المصاريف منه.': 'Start by receiving the money handed to you, then record expenses from it.',
    'البيان': 'Description', 'وارد': 'In', 'صادر': 'Out',

    // ─ التقارير
    'كشف حساب': 'Account statement', 'البداية': 'Start',
    'في نافذة الطباعة اختر «حفظ PDF» — على الآيفون: مشاركة ثم «حفظ في الملفات». روابط المستندات تبقى قابلة للنقر داخل الملف.':
        'In the print dialog choose "Save as PDF" — on iPhone: Share, then "Save to Files". Document links stay clickable inside the file.',
    'تنزيل PDF': 'Download PDF', 'أضف شعار منشأتك وبياناتها لتظهر في الكشف ←': 'Add your organisation logo and details to show them on the statement →',
    'الرصيد الافتتاحي': 'Opening balance', 'الوارد': 'Money in', 'الصادر': 'Money out', 'الرصيد الختامي': 'Closing balance',
    'المستند': 'Document', 'رصيدٌ مرحَّل': 'Balance brought forward', 'درايف': 'Drive', 'عرض': 'View',
    'الإجمالي ({n} حركة)': 'Total ({n} transactions)', 'الإجمالي': 'Total',
    'ضريبة القيمة المضافة ضمن الصادر:': 'VAT included in money out:',
    'المستندات المرفقة: {a} من {b} حركة': 'Documents attached: {a} of {b} transactions', '{n} مصروفٍ بلا مستند': '{n} expenses without a document',
    'روابط «عرض» صالحةٌ سنةً من تاريخ الإصدار، وروابط «درايف» تفتح الملف في Google Drive لمن له صلاحية على المجلد.':
        '"View" links are valid for one year from the issue date; "Drive" links open the file in Google Drive for anyone with access to the folder.',
    'تقرير تصفية عهدة': 'Custody settlement report', 'اطبعه أو احفظه PDF من نافذة الطباعة': 'Print it or save it as PDF from the print dialog',
    'طباعة': 'Print', 'الفترة': 'Period', 'الحالة': 'Status',
    'إجمالي المستلم': 'Total received', 'إجمالي المصروف': 'Total spent', 'منه ضريبة': 'of which VAT',
    'المتبقّي للإرجاع': 'Balance to return', 'المستحقّ لصاحب العهدة': 'Due to the custodian',
    'يُحوَّل المستحقّ إلى الآيبان:': 'Amount due to be transferred to IBAN:',
    'المبالغ المستلمة': 'Money received', 'المصروفات ({n})': 'Expenses ({n})',
    'تنبيه: {n} مصروفٍ بلا إيصال مرفق.': 'Note: {n} expenses have no receipt attached.', 'حسب التصنيف': 'By category',
    'الإيصالات المرفقة': 'Attached receipts', 'مستندات PDF مرفقة بالبنود: {list} — تُطبع منفصلة.': 'PDF documents attached to items {list} — print separately.',
    'صاحب العهدة': 'Custodian', 'المراجِع / المعتمِد': 'Reviewer / Approver', 'التوقيع والتاريخ': 'Signature & date',
    'أُعدّ بتطبيق عُهدة': 'Prepared with Ohda', 'الرقم الضريبي': 'VAT number', 'السجل التجاري': 'CR number',
    'الرقم الوظيفي': 'Employee no.', 'المسمّى الوظيفي': 'Job title', 'الإدارة': 'Department', 'البريد': 'Email',
    'الجوال': 'Mobile', 'الآيبان': 'IBAN', 'البنك': 'Bank',

    // ─ الميزانية
    'مصروف هذا الشهر من الميزانية': 'Budgeted spending this month', 'اليوم {a} من {b}': 'Day {a} of {b}',
    'حدّد ميزانية لتصنيفاتك ليظهر هنا تقدّمك وتنبيهك قبل التجاوز.': 'Set budgets for your categories to track progress and get warned before overspending.',
    'كل مصروف الشهر': "All of this month's spending", 'منه خارج الميزانيات': 'of which outside budgets',
    'التصنيفات': 'Categories', 'بلا سقف': 'No limit',
    'حذف التصنيف؟ تبقى حركاته مسجّلة بلا تصنيف.': 'Delete this category? Its transactions stay, uncategorised.',
    'حُذف التصنيف': 'Category deleted', 'حُفظ': 'Saved', 'تعديل التصنيف': 'Edit category', 'تصنيف جديد': 'New category',
    'الميزانية الشهرية': 'Monthly budget', 'اتركها صفراً إن لم ترد سقفاً': 'Leave at zero for no limit', 'الأيقونة': 'Icon',

    // ─ الإعدادات
    'مدير': 'Admin', 'إعداد الحساب': 'Account setup', 'لغة التطبيق': 'App language',
    'الشعار واسم المنشأة والرقم الضريبي وبيانات المستفيد': 'Logo, organisation name, VAT number and beneficiary details',
    'الميزانية والتصنيفات': 'Budgets & categories', 'سقفٌ شهري لكل تصنيف': 'A monthly limit per category',
    'رصيدٌ جارٍ وروابط المستندات': 'Running balance and document links', 'تصدير الحركات': 'Export transactions',
    'ملف Excel بكل ما سجّلته': 'An Excel file of everything you recorded', 'الحركات المحذوفة تُستعاد من هنا': 'Restore deleted transactions here',
    'تغيير كلمة المرور': 'Change password', 'تسجيل الخروج': 'Sign out',
    'كلمتا المرور الجديدتان غير متطابقتين': 'The new passwords do not match', 'تغيّرت كلمة المرور': 'Password changed',
    'الحالية': 'Current', 'الجديدة': 'New', 'أعد كتابتها': 'Repeat it',
    'رُبط Google Drive': 'Google Drive linked', 'لم يكتمل ربط Drive — أعد المحاولة': 'Drive linking did not complete — try again',
    'فكّ ربط Drive؟ تبقى الملفات في درايفك وعلى الخادم، وتتوقّف الرفعات الجديدة.': 'Unlink Drive? Files stay in your Drive and on the server; new uploads stop.',
    'فُكّ الربط': 'Unlinked', 'مجلد «عُهدة» في درايفك، وتحته مجلد لكل مستخدم': 'An «Ohda» folder in your Drive, with a folder per user',
    'مربوط': 'Linked',
    'مفاتيح Google لم تُضف إلى الخادم بعد. الملفات محفوظة على الخادم الآن، وتُرفع كلها إلى درايف تلقائياً فور الربط.':
        'Google keys have not been added to the server yet. Files are stored on the server for now and will all upload to Drive automatically once linked.',
    'اربط حساب Google Drive': 'Link Google Drive', 'رُفعت': 'Uploaded', 'بالانتظار': 'Pending', 'تعثّرت': 'Failed',
    'آخر خطأ:': 'Last error:', 'إعادة الربط': 'Relink', 'فكّ الربط': 'Unlink',
    'المستخدمون': 'Users', 'لكل مستخدمٍ بياناته وحده — لا يرى أحدٌ بيانات غيره': "Each user's data is private — nobody sees anyone else's",
    'حُفظ المستخدم': 'User saved', 'أُنشئ الحساب': 'Account created',
    'أُنشئ حساب {n} — أرسل له بيانات الدخول': "{n}'s account is ready — send them the login details",
    'حُفظ حساب {n}': "{n}'s account saved", 'أرسل بياناته واتساب': 'Send login via WhatsApp',
    'لم تُغيَّر كلمة المرور، فالرسالة بلا كلمة مرور.': "The password wasn't changed, so the message has no password.",
    'موقوف': 'Suspended', 'آخر دخول': 'last login', 'أرسل الرابط واتساب': 'Send the link via WhatsApp',
    'تعديل المستخدم': 'Edit user', 'مستخدم جديد': 'New user', 'أمي، عهدة العمل…': 'Mum, work custody…',
    'كلمة مرور جديدة': 'New password', 'اتركها فارغة لتبقى كما هي': 'Leave empty to keep it',
    'جوال واتساب': 'WhatsApp number', 'لإرسال بيانات الدخول مباشرة': 'To send the login details directly',
    'لغة المستخدم': "User's language", 'الحساب فعّال': 'Account active',

    // ─ إعداد الحساب
    'المنشأة': 'Organisation', 'تغيير الشعار': 'Change logo', 'رفع شعار المنشأة': 'Upload organisation logo',
    'PNG بخلفية شفافة أفضل': 'A PNG with a transparent background works best',
    'اسم المنشأة': 'Organisation name', 'اسم المنشأة بالإنجليزية': 'Organisation name (English)', '١٥ رقماً': '15 digits',
    'العنوان': 'Address', 'هاتف المنشأة': 'Organisation phone', 'بريد المنشأة': 'Organisation email',
    'المستفيد (صاحب العهدة)': 'Beneficiary (custodian)', 'اسمك في التطبيق': 'Your name in the app',
    'الاسم كما يظهر في الكشوف': 'Name as shown on statements', 'اتركه فارغاً ليُستعمل اسمك': 'Leave empty to use your name',
    'البريد الإلكتروني': 'Email', 'رقم الجوال': 'Mobile number', 'لتحويل المستحقّ عند التصفية': 'For transferring the amount due at settlement',
    'التقارير والاعتماد': 'Reports & approval', 'اسم المعتمِد': 'Approver name', 'صفته': 'Approver title',
    'ملاحظة أسفل التقارير': 'Footer note on reports', 'تظهر في ذيل كشف الحساب وتقرير التصفية': 'Shown at the bottom of statements and settlement reports',
    'حُفظ إعداد الحساب': 'Account setup saved', 'رُفع الشعار': 'Logo uploaded', 'أُزيل الشعار': 'Logo removed',

    // ─ رسائل الخادم
    'إجراء غير معروف': 'Unknown action', 'انتهت الجلسة، سجّل الدخول من جديد': 'Session expired — please sign in again',
    'اسم التصنيف مطلوب': 'Category name is required', 'اسم العهدة مطلوب': 'Fund name is required', 'الاسم مطلوب': 'Name is required',
    'اسم الدخول أو كلمة المرور غير صحيحة': 'Incorrect username or password', 'اسم الدخول مستعمل': 'Username already taken',
    'اسم الدخول: حروف إنجليزية وأرقام، ٣ أحرف فأكثر': 'Username: English letters and numbers, at least 3 characters',
    'الآيبان السعودي يبدأ بـ SA ثم ٢٢ رقماً': 'A Saudi IBAN starts with SA followed by 22 digits',
    'البريد الإلكتروني غير صحيح': 'Invalid email address', 'التهيئة مغلقة — يوجد مدير': 'Setup is closed — an admin exists',
    'الحد خمسة عشر ميجابايت': 'The limit is 15 MB', 'الحركة غير موجودة': 'Transaction not found', 'الحساب موقوف': 'Account suspended',
    'الرابط منتهٍ': 'Link expired', 'الرقم الضريبي ١٥ رقماً': 'The VAT number must be 15 digits',
    'الشعار ثلاثة ميجابايت كحدٍّ أقصى': 'The logo must be 3 MB or less', 'الشعار صورة PNG أو JPG': 'The logo must be a PNG or JPG image',
    'العهدة غير موجودة': 'Fund not found', 'المبلغ مطلوب': 'Amount is required', 'المستند أطول من المتوقّع': 'The document is longer than expected',
    'الملف غير موجود': 'File not found', 'تعذّر إنشاء مجلد الملفات': 'Could not create the files folder',
    'تعذّر الاتصال بقاعدة البيانات': 'Could not connect to the database', 'تعذّرت القراءة (': 'Could not read (',
    'رفض القارئ هذا المستند': 'The reader declined this document', 'رقم الجوال غير صحيح': 'Invalid mobile number',
    'صور أو PDF فقط': 'Images or PDF only', 'غير موجود': 'Not found', 'فشل الحفظ': 'Saving failed',
    'قراءة الإيصالات غير مفعّلة على الخادم': 'Receipt reading is not enabled on the server',
    'كلمة المرور الجديدة ثمانية أحرف فأكثر': 'The new password must be at least 8 characters',
    'كلمة المرور الحالية غير صحيحة': 'Current password is incorrect', 'كلمة المرور ثمانية أحرف فأكثر': 'Password must be at least 8 characters',
    'للمدير فقط': 'Admin only', 'لم يصل الملف': 'The file did not arrive', 'لم يُفهم ردّ القارئ': "Could not understand the reader's reply",
    'محاولات كثيرة — انتظر ربع ساعة': 'Too many attempts — wait 15 minutes',
    'مفاتيح Google غير مضافة على الخادم بعد': 'Google keys are not on the server yet',
    'لا اتصال بالإنترنت': 'No internet connection', 'ردّ غير مفهوم من الخادم': 'Unexpected server response',

    // ─ الأمان والدخول
    "{n} د": "{n} min",
    "آخر استعمال": "last used",
    "أبداً": "Never",
    "أنشئ حساب المدير لتبدأ": "Create the admin account to begin",
    "أهلاً بك": "Welcome back",
    "أو بكلمة المرور": "or with your password",
    "أُزيل الجهاز": "Device removed",
    "أُضيف": "added",
    "إخفاء": "Hide",
    "إظهار": "Show",
    "إزالة «{n}» من أجهزة الدخول بالبصمة؟": "Remove «{n}» from biometric sign-in devices?",
    "إعداد التطبيق": "App setup",
    "ادخل في المرّة القادمة بلمسةٍ واحدة بدل كلمة المرور. البصمة لا تغادر جهازك.": "Next time, sign in with one touch instead of your password. Your biometrics never leave your device.",
    "الأمان": "Security",
    "الخروج التلقائي بعد عدم النشاط": "Auto sign-out after inactivity",
    "الدخول بالبصمة": "Sign in with fingerprint",
    "الدخول بـ Face ID": "Sign in with Face ID",
    "بيانات غير صالحة": "Invalid data",
    "تعذّر التحقّق من البصمة": "Biometric verification failed",
    "تعذّر التفعيل": "Could not enable",
    "تعذّرت قراءة بيانات الجهاز": "Could not read the device data",
    "خرجتَ تلقائياً بعد فترةٍ بلا نشاط، حمايةً لبياناتك.": "You were signed out automatically after a period of inactivity, to protect your data.",
    "ساعة": "1 hour",
    "سجّل دخولك لتكمل": "Sign in to continue",
    "صوّر الإيصال ويقرأه التطبيق لك": "Snap a receipt and the app reads it for you",
    "فعّله على هذا الجهاز": "Enable on this device",
    "فعّلها على هذا الجهاز": "Enable on this device",
    "فُعّل الدخول بالبصمة": "Fingerprint sign-in enabled",
    "فُعّل الدخول بـ Face ID": "Face ID sign-in enabled",
    "كشف حساب PDF بروابط المستندات": "PDF statements with document links",
    "لا أجهزة مسجّلة بعد.": "No devices registered yet.",
    "لم يُتحقَّق من البصمة": "Biometrics were not verified",
    "ليس الآن": "Not now",
    "نوع مفتاح غير مدعوم": "Unsupported key type",
    "هذا الجهاز أو المتصفّح لا يدعم الدخول بالبصمة.": "This device or browser doesn't support biometric sign-in.",
    "هذه البصمة غير مسجّلة — ادخل بكلمة المرور ثم فعّلها من الإعدادات": "This biometric key is not registered — sign in with your password, then enable it in Settings",
    "يُطبَّق على هذا الجهاز، ويحتسب حتى لو أُغلق التطبيق.": "Applies to this device, and counts even while the app is closed.",
    "مصدر الطلب غير موثوق": "Untrusted request origin",
    "انتهت مهلة التحقّق، أعد المحاولة": "Verification timed out — try again",

    // ─ الصفحات المتعدّدة
    "صفحة": "Page",
    "ملف": "File",
    "{n} صفحات تُقرأ معاً كمستندٍ واحد": "{n} pages read together as one document",
    "أعد القراءة": "Read again",
    "يقرأ {n} صفحات…": "Reading {n} pages…",
};
